### ISSUE TITLE
Add option to configure RCON

### ISSUE THREAD

**Issue by felixklauke** [felixklauke/paper-docker#47]

**Comment by FelixKlauke** [comment]
The rcon credentials should be configurable via environment.

Example
```yaml
[...]
services:
  minecraft:
    [...]
    env:
      - RCON_ENABLED=true
      - RCON_PASSWORD=1234567
    ports:
      - 25566:25566
```
